import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/modules/base/styles/base.css";
import { ReduxProvider } from "@/lib/ReduxProvider";
import { TenantProvider } from "@/lib/tenant";
import LayoutSwitcher from "@/modules/base/components/LayoutSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        data-new-gr-c-s-check-loaded="14.1258.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
        className="body"
      >
        <ReduxProvider>
          <TenantProvider>
            <LayoutSwitcher>{children}</LayoutSwitcher>
          </TenantProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
